-- ============================================================================
-- 016_staff_control_dashboards.sql
-- Dashboard personalizable por usuario, control de turnos de staff con cierre
-- de caja y snapshot de stock, control de personal de gimnasio,
-- autenticación multi-método para staff.
-- ============================================================================

-- ============================================================================
-- 1. DASHBOARD PERSONALIZABLE POR USUARIO
-- ============================================================================

-- Configuración de dashboard por usuario: qué widgets ve, en qué orden, tamaño
CREATE TABLE IF NOT EXISTS nm_dashboard_configs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id int NOT NULL DEFAULT 1,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  dashboard_type text NOT NULL DEFAULT 'player', -- 'admin' | 'player'
  layout jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- layout is array of: { widget_id: string, visible: boolean, order: number,
  --   size: 'sm'|'md'|'lg'|'full', col_span: number, row_span: number,
  --   config: { ... widget-specific settings } }
  theme jsonb DEFAULT '{}'::jsonb,
  -- theme overrides: { accentColor, cardStyle, compactMode, etc. }
  sidebar_collapsed boolean DEFAULT false,
  default_page text, -- which page loads first after login
  quick_actions jsonb DEFAULT '[]'::jsonb,
  -- array of { action_id: string, label: string, visible: boolean, order: number }
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, dashboard_type)
);

-- Widget catalog: define all available widgets with their defaults
CREATE TABLE IF NOT EXISTS nm_dashboard_widgets (
  id text PRIMARY KEY, -- e.g. 'kpi_bookings_today', 'live_cash', 'chart_revenue'
  club_id int NOT NULL DEFAULT 1,
  dashboard_type text NOT NULL DEFAULT 'admin', -- which dashboard this belongs to
  name text NOT NULL,
  description text,
  category text NOT NULL DEFAULT 'general', -- 'kpi' | 'live' | 'chart' | 'list' | 'action'
  default_size text DEFAULT 'md', -- sm | md | lg | full
  default_visible boolean DEFAULT true,
  default_order int DEFAULT 0,
  icon text, -- lucide icon name
  min_role text DEFAULT 'player', -- minimum role to see this widget
  is_active boolean DEFAULT true,
  config_schema jsonb DEFAULT '{}'::jsonb -- JSON schema for widget-specific config
);

-- ============================================================================
-- 2. CONTROL DE TURNOS DE STAFF CON CIERRE DE CAJA Y STOCK
-- ============================================================================

-- Enhance nm_staff_shifts: add authentication method and shift type
ALTER TABLE nm_staff_shifts
  ADD COLUMN IF NOT EXISTS auth_method text, -- 'pin' | 'nfc' | 'fingerprint' | 'facial' | 'manual'
  ADD COLUMN IF NOT EXISTS shift_type text DEFAULT 'regular', -- 'regular' | 'extra' | 'replacement'
  ADD COLUMN IF NOT EXISTS break_start timestamptz,
  ADD COLUMN IF NOT EXISTS break_end timestamptz,
  ADD COLUMN IF NOT EXISTS break_minutes int DEFAULT 0,
  ADD COLUMN IF NOT EXISTS net_minutes int, -- total worked minus breaks
  ADD COLUMN IF NOT EXISTS overtime_minutes int DEFAULT 0,
  ADD COLUMN IF NOT EXISTS approved_by uuid REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS approved_at timestamptz,
  ADD COLUMN IF NOT EXISTS ip_address text,
  ADD COLUMN IF NOT EXISTS device_info text;

-- Staff authentication credentials (PIN, NFC, fingerprint, facial)
CREATE TABLE IF NOT EXISTS nm_staff_credentials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id int NOT NULL DEFAULT 1,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type text NOT NULL, -- 'pin' | 'nfc' | 'fingerprint' | 'facial'
  credential_data text NOT NULL, -- hashed PIN, NFC tag ID, fingerprint template hash, facial encoding ref
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  last_used_at timestamptz,
  expires_at timestamptz,
  UNIQUE(user_id, type)
);

CREATE INDEX IF NOT EXISTS idx_nm_staff_cred_type ON nm_staff_credentials(type, credential_data) WHERE is_active = true;

-- Cash shift closings (when staff changes, mandatory cash count)
CREATE TABLE IF NOT EXISTS nm_cash_closings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id int NOT NULL DEFAULT 1,
  shift_id bigint REFERENCES nm_staff_shifts(id),
  closed_by uuid NOT NULL REFERENCES auth.users(id),
  opened_at timestamptz NOT NULL,
  closed_at timestamptz NOT NULL DEFAULT now(),

  -- Expected amounts (system-calculated from nm_cash_register)
  expected_cash numeric(10,2) DEFAULT 0,
  expected_card numeric(10,2) DEFAULT 0,
  expected_transfer numeric(10,2) DEFAULT 0,
  expected_bizum numeric(10,2) DEFAULT 0,
  expected_total numeric(10,2) DEFAULT 0,

  -- Actual counted amounts (staff enters these)
  actual_cash numeric(10,2) DEFAULT 0,
  actual_card numeric(10,2) DEFAULT 0,
  actual_transfer numeric(10,2) DEFAULT 0,
  actual_bizum numeric(10,2) DEFAULT 0,
  actual_total numeric(10,2) DEFAULT 0,

  -- Differences
  diff_cash numeric(10,2) GENERATED ALWAYS AS (actual_cash - expected_cash) STORED,
  diff_card numeric(10,2) GENERATED ALWAYS AS (actual_card - expected_card) STORED,
  diff_transfer numeric(10,2) GENERATED ALWAYS AS (actual_transfer - expected_transfer) STORED,
  diff_bizum numeric(10,2) GENERATED ALWAYS AS (actual_bizum - expected_bizum) STORED,
  diff_total numeric(10,2) GENERATED ALWAYS AS (actual_total - expected_total) STORED,

  -- Counts
  total_transactions int DEFAULT 0,
  total_bookings int DEFAULT 0,
  total_sales int DEFAULT 0,

  notes text,
  status text DEFAULT 'open', -- 'open' | 'closed' | 'reviewed' | 'approved'
  reviewed_by uuid REFERENCES auth.users(id),
  reviewed_at timestamptz,

  created_at timestamptz DEFAULT now()
);

-- Stock snapshots at shift change
CREATE TABLE IF NOT EXISTS nm_stock_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id int NOT NULL DEFAULT 1,
  cash_closing_id bigint REFERENCES nm_cash_closings(id),
  taken_by uuid NOT NULL REFERENCES auth.users(id),
  taken_at timestamptz DEFAULT now(),
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- items: [{ product_id, product_name, expected_stock, actual_stock, difference }]
  total_products int DEFAULT 0,
  products_with_diff int DEFAULT 0,
  notes text,
  status text DEFAULT 'pending' -- 'pending' | 'reviewed' | 'approved'
);

-- Shift handover log (complete record of what happened during handover)
CREATE TABLE IF NOT EXISTS nm_shift_handovers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id int NOT NULL DEFAULT 1,
  outgoing_user_id uuid NOT NULL REFERENCES auth.users(id),
  incoming_user_id uuid NOT NULL REFERENCES auth.users(id),
  outgoing_shift_id bigint REFERENCES nm_staff_shifts(id),
  incoming_shift_id bigint REFERENCES nm_staff_shifts(id),
  cash_closing_id bigint REFERENCES nm_cash_closings(id),
  stock_snapshot_id bigint REFERENCES nm_stock_snapshots(id),
  handover_at timestamptz DEFAULT now(),
  notes text,
  -- Checklist items completed
  checklist jsonb DEFAULT '[]'::jsonb,
  -- [{ item: 'Caja cuadrada', done: true }, { item: 'Stock verificado', done: true }, ...]
  status text DEFAULT 'completed', -- 'in_progress' | 'completed' | 'flagged'
  created_at timestamptz DEFAULT now()
);

-- ============================================================================
-- 3. CONTROL DE PERSONAL DE GIMNASIO
-- ============================================================================

-- Gym access logs (separate from general access — tracks gym-specific entries)
CREATE TABLE IF NOT EXISTS nm_gym_access_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id int NOT NULL DEFAULT 1,
  user_id uuid NOT NULL REFERENCES auth.users(id),
  membership_id bigint REFERENCES nm_gym_memberships(id),
  access_point_id bigint REFERENCES nm_access_points(id),
  auth_method text NOT NULL, -- 'qr' | 'nfc' | 'pin' | 'fingerprint' | 'facial' | 'manual'
  direction text DEFAULT 'in', -- 'in' | 'out'
  granted boolean DEFAULT true,
  denial_reason text,
  check_in_at timestamptz DEFAULT now(),
  check_out_at timestamptz,
  duration_minutes int,
  zone text, -- 'sala_musculacion' | 'sala_cardio' | 'piscina' | 'spa' | 'clases'
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_nm_gym_access_user ON nm_gym_access_logs(user_id, check_in_at DESC);
CREATE INDEX IF NOT EXISTS idx_nm_gym_access_date ON nm_gym_access_logs(club_id, check_in_at DESC);

-- Gym staff activity log (tracks what gym staff does: changes, incidents, etc.)
CREATE TABLE IF NOT EXISTS nm_gym_staff_activity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id int NOT NULL DEFAULT 1,
  user_id uuid NOT NULL REFERENCES auth.users(id),
  shift_id bigint REFERENCES nm_staff_shifts(id),
  action_type text NOT NULL,
  -- 'check_in' | 'check_out' | 'membership_change' | 'class_change' | 'incident' |
  -- 'equipment_issue' | 'product_sale' | 'cash_movement' | 'manual_entry' | 'other'
  description text,
  reference_type text, -- 'membership' | 'class' | 'session' | 'product' | 'cash' | null
  reference_id bigint,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_nm_gym_staff_act ON nm_gym_staff_activity(club_id, user_id, created_at DESC);

-- ============================================================================
-- 4. STAFF TIME TRACKING & REPORTS
-- ============================================================================

-- Monthly time summary per staff (materialized/computed)
CREATE TABLE IF NOT EXISTS nm_staff_time_summary (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id int NOT NULL DEFAULT 1,
  user_id uuid NOT NULL REFERENCES auth.users(id),
  year int NOT NULL,
  month int NOT NULL,
  total_shifts int DEFAULT 0,
  total_minutes int DEFAULT 0,
  overtime_minutes int DEFAULT 0,
  break_minutes int DEFAULT 0,
  net_minutes int DEFAULT 0,
  absences int DEFAULT 0,
  late_arrivals int DEFAULT 0, -- arrived > 10 min after scheduled
  early_departures int DEFAULT 0,
  avg_shift_minutes int DEFAULT 0,
  computed_at timestamptz DEFAULT now(),
  UNIQUE(user_id, year, month)
);

-- ============================================================================
-- 5. TRIGGERS & FUNCTIONS
-- ============================================================================

-- Auto-compute net_minutes on staff_shifts when check_out happens
CREATE OR REPLACE FUNCTION nm_trigger_shift_net_minutes()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.check_out IS NOT NULL AND NEW.check_in IS NOT NULL THEN
    NEW.net_minutes := GREATEST(0,
      EXTRACT(EPOCH FROM (NEW.check_out - NEW.check_in))::int / 60
      - COALESCE(NEW.break_minutes, 0)
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_nm_shift_net_minutes ON nm_staff_shifts;
CREATE TRIGGER tr_nm_shift_net_minutes
BEFORE UPDATE ON nm_staff_shifts
FOR EACH ROW EXECUTE FUNCTION nm_trigger_shift_net_minutes();

-- Auto-compute gym access duration on checkout
CREATE OR REPLACE FUNCTION nm_trigger_gym_access_duration()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.check_out_at IS NOT NULL AND NEW.check_in_at IS NOT NULL THEN
    NEW.duration_minutes := GREATEST(0,
      EXTRACT(EPOCH FROM (NEW.check_out_at - NEW.check_in_at))::int / 60
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_nm_gym_access_duration ON nm_gym_access_logs;
CREATE TRIGGER tr_nm_gym_access_duration
BEFORE UPDATE ON nm_gym_access_logs
FOR EACH ROW EXECUTE FUNCTION nm_trigger_gym_access_duration();

-- Log gym staff activity automatically when key tables change
CREATE OR REPLACE FUNCTION nm_trigger_gym_activity_log()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  v_user uuid;
  v_action text;
  v_desc text;
  v_ref_type text;
  v_ref_id bigint;
BEGIN
  v_user := auth.uid();
  IF v_user IS NULL THEN RETURN NEW; END IF;

  IF TG_TABLE_NAME = 'nm_gym_memberships' THEN
    v_ref_type := 'membership';
    v_ref_id := NEW.id;
    IF TG_OP = 'INSERT' THEN
      v_action := 'membership_change'; v_desc := 'Nueva membresía creada';
    ELSIF TG_OP = 'UPDATE' AND OLD.status != NEW.status THEN
      v_action := 'membership_change'; v_desc := 'Membresía: ' || OLD.status || ' → ' || NEW.status;
    ELSE
      RETURN NEW;
    END IF;
  ELSIF TG_TABLE_NAME = 'nm_gym_sessions' THEN
    v_ref_type := 'session';
    v_ref_id := NEW.id;
    IF TG_OP = 'INSERT' THEN
      v_action := 'check_in'; v_desc := 'Check-in gimnasio';
    ELSIF TG_OP = 'UPDATE' AND NEW.check_out IS NOT NULL AND OLD.check_out IS NULL THEN
      v_action := 'check_out'; v_desc := 'Check-out gimnasio';
    ELSE
      RETURN NEW;
    END IF;
  ELSE
    RETURN NEW;
  END IF;

  INSERT INTO nm_gym_staff_activity (club_id, user_id, action_type, description, reference_type, reference_id)
  VALUES (1, v_user, v_action, v_desc, v_ref_type, v_ref_id);

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_nm_gym_act_memberships ON nm_gym_memberships;
CREATE TRIGGER tr_nm_gym_act_memberships
AFTER INSERT OR UPDATE ON nm_gym_memberships
FOR EACH ROW EXECUTE FUNCTION nm_trigger_gym_activity_log();

DROP TRIGGER IF EXISTS tr_nm_gym_act_sessions ON nm_gym_sessions;
CREATE TRIGGER tr_nm_gym_act_sessions
AFTER INSERT OR UPDATE ON nm_gym_sessions
FOR EACH ROW EXECUTE FUNCTION nm_trigger_gym_activity_log();

-- ============================================================================
-- 6. RLS POLICIES
-- ============================================================================

ALTER TABLE nm_dashboard_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE nm_dashboard_widgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE nm_staff_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE nm_cash_closings ENABLE ROW LEVEL SECURITY;
ALTER TABLE nm_stock_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE nm_shift_handovers ENABLE ROW LEVEL SECURITY;
ALTER TABLE nm_gym_access_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE nm_gym_staff_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE nm_staff_time_summary ENABLE ROW LEVEL SECURITY;

-- Dashboard: users can read/write their own config
CREATE POLICY "users_own_dashboard" ON nm_dashboard_configs
  FOR ALL TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Dashboard widgets: anyone can read
CREATE POLICY "public_read_widgets" ON nm_dashboard_widgets
  FOR SELECT TO authenticated USING (true);

-- Admin-only write for widgets
CREATE POLICY "admin_write_widgets" ON nm_dashboard_widgets
  FOR ALL TO authenticated
  USING (nm_is_admin())
  WITH CHECK (nm_is_admin());

-- Staff credentials: admin can manage, user can read own
CREATE POLICY "admin_manage_staff_creds" ON nm_staff_credentials
  FOR ALL TO authenticated
  USING (nm_is_admin())
  WITH CHECK (nm_is_admin());

CREATE POLICY "user_read_own_creds" ON nm_staff_credentials
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- Cash closings: admin only
CREATE POLICY "admin_cash_closings" ON nm_cash_closings
  FOR ALL TO authenticated
  USING (nm_is_admin())
  WITH CHECK (nm_is_admin());

-- Stock snapshots: admin only
CREATE POLICY "admin_stock_snapshots" ON nm_stock_snapshots
  FOR ALL TO authenticated
  USING (nm_is_admin())
  WITH CHECK (nm_is_admin());

-- Shift handovers: admin only
CREATE POLICY "admin_shift_handovers" ON nm_shift_handovers
  FOR ALL TO authenticated
  USING (nm_is_admin())
  WITH CHECK (nm_is_admin());

-- Gym access logs: admin + own
CREATE POLICY "admin_gym_access" ON nm_gym_access_logs
  FOR ALL TO authenticated
  USING (nm_is_admin())
  WITH CHECK (nm_is_admin());

CREATE POLICY "user_read_own_gym_access" ON nm_gym_access_logs
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- Gym staff activity: admin only
CREATE POLICY "admin_gym_staff_activity" ON nm_gym_staff_activity
  FOR ALL TO authenticated
  USING (nm_is_admin())
  WITH CHECK (nm_is_admin());

-- Staff time summary: admin + own
CREATE POLICY "admin_time_summary" ON nm_staff_time_summary
  FOR ALL TO authenticated
  USING (nm_is_admin())
  WITH CHECK (nm_is_admin());

CREATE POLICY "user_read_own_time" ON nm_staff_time_summary
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- ============================================================================
-- 7. SEED DEFAULT DASHBOARD WIDGETS
-- ============================================================================

INSERT INTO nm_dashboard_widgets (id, dashboard_type, name, description, category, default_size, default_visible, default_order, icon, min_role) VALUES
-- Admin widgets
('kpi_bookings_today', 'admin', 'Reservas hoy', 'Cantidad de reservas del día', 'kpi', 'sm', true, 1, 'CalendarCheck', 'admin'),
('kpi_revenue_today', 'admin', 'Ingresos hoy', 'Total de ingresos del día', 'kpi', 'sm', true, 2, 'DollarSign', 'admin'),
('kpi_members_active', 'admin', 'Miembros activos', 'Total de miembros activos', 'kpi', 'sm', true, 3, 'Users', 'admin'),
('kpi_tournaments', 'admin', 'Torneos activos', 'Torneos en curso', 'kpi', 'sm', true, 4, 'Trophy', 'admin'),
('kpi_leagues', 'admin', 'Ligas activas', 'Ligas en curso', 'kpi', 'sm', true, 5, 'Medal', 'admin'),
('kpi_gym_members', 'admin', 'Gym miembros', 'Membresías activas de gimnasio', 'kpi', 'sm', true, 6, 'Dumbbell', 'admin'),
('kpi_access_today', 'admin', 'Accesos hoy', 'Entradas registradas hoy', 'kpi', 'sm', true, 7, 'DoorOpen', 'admin'),
('kpi_access_denied', 'admin', 'Accesos denegados', 'Accesos denegados hoy', 'kpi', 'sm', true, 8, 'ShieldX', 'admin'),
('kpi_subscriptions', 'admin', 'Suscripciones', 'Suscripciones activas', 'kpi', 'sm', true, 9, 'CreditCard', 'admin'),
('kpi_invoices_overdue', 'admin', 'Facturas vencidas', 'Facturas pendientes de pago', 'kpi', 'sm', true, 10, 'FileWarning', 'admin'),
('kpi_posts_week', 'admin', 'Posts (7 días)', 'Posts de la última semana', 'kpi', 'sm', true, 11, 'MessageSquare', 'admin'),
('kpi_challenges', 'admin', 'Retos activos', 'Retos en curso', 'kpi', 'sm', true, 12, 'Target', 'admin'),
('kpi_staff_on_shift', 'admin', 'Staff en turno', 'Personal trabajando ahora', 'kpi', 'sm', true, 13, 'UserCog', 'admin'),
('live_bookings', 'admin', 'Reservas de hoy', 'Últimas reservas del día', 'live', 'md', true, 20, 'Calendar', 'admin'),
('live_cash', 'admin', 'Movimientos de caja', 'Últimos movimientos de caja', 'live', 'md', true, 21, 'Banknote', 'admin'),
('live_access', 'admin', 'Últimos accesos', 'Log de accesos reciente', 'live', 'md', true, 22, 'DoorOpen', 'admin'),
('live_invoices_overdue', 'admin', 'Facturas vencidas', 'Facturas pendientes', 'live', 'md', true, 23, 'AlertTriangle', 'admin'),
('chart_revenue_week', 'admin', 'Ingresos semanal', 'Gráfico de ingresos últimos 7 días', 'chart', 'lg', false, 30, 'BarChart3', 'admin'),
('chart_occupancy', 'admin', 'Ocupación pistas', 'Ocupación de pistas por franja', 'chart', 'lg', false, 31, 'BarChart', 'admin'),
('chart_access_week', 'admin', 'Accesos semanal', 'Accesos diarios últimos 7 días', 'chart', 'lg', false, 32, 'LineChart', 'admin'),
('list_staff_shifts', 'admin', 'Staff en turno', 'Personal activo actualmente', 'list', 'md', false, 40, 'Users', 'admin'),
('list_gym_checkins', 'admin', 'Check-ins gym', 'Personas en el gimnasio ahora', 'list', 'md', false, 41, 'Dumbbell', 'admin'),
('action_quick_booking', 'admin', 'Reserva rápida', 'Crear reserva rápida', 'action', 'sm', false, 50, 'Plus', 'admin'),
('action_cash_entry', 'admin', 'Entrada de caja', 'Registrar movimiento de caja', 'action', 'sm', false, 51, 'PlusCircle', 'admin'),
-- Player widgets
('kpi_my_bookings', 'player', 'Mis reservas', 'Reservas activas', 'kpi', 'sm', true, 1, 'Calendar', 'player'),
('kpi_my_matches', 'player', 'Partidos jugados', 'Total de partidos', 'kpi', 'sm', true, 2, 'Swords', 'player'),
('kpi_my_ranking', 'player', 'Mi ranking', 'Posición en el ranking', 'kpi', 'sm', true, 3, 'TrendingUp', 'player'),
('kpi_my_winrate', 'player', 'Win Rate', 'Porcentaje de victorias', 'kpi', 'sm', true, 4, 'Percent', 'player'),
('live_my_bookings', 'player', 'Próximas reservas', 'Reservas pendientes', 'live', 'md', true, 20, 'Calendar', 'player'),
('live_my_subscription', 'player', 'Mi suscripción', 'Plan y renovación', 'live', 'md', true, 21, 'CreditCard', 'player'),
('live_my_challenges', 'player', 'Mis retos', 'Progreso en retos', 'live', 'md', true, 22, 'Target', 'player'),
('live_my_profile', 'player', 'Tu perfil', 'Estado de tu ficha', 'live', 'md', true, 23, 'UserCheck', 'player'),
('action_book', 'player', 'Reservar', 'Hacer nueva reserva', 'action', 'sm', true, 50, 'CalendarPlus', 'player'),
('action_find_match', 'player', 'Buscar partido', 'Encontrar compañeros', 'action', 'sm', true, 51, 'Search', 'player'),
('action_my_access', 'player', 'Mi acceso', 'Ver mi QR de acceso', 'action', 'sm', true, 52, 'QrCode', 'player'),
('action_training', 'player', 'Entrenamiento', 'Ver mi plan', 'action', 'sm', true, 53, 'ClipboardList', 'player'),
('action_challenges', 'player', 'Retos', 'Ver retos activos', 'action', 'sm', true, 54, 'Target', 'player'),
('action_community', 'player', 'Comunidad', 'Feed social', 'action', 'sm', true, 55, 'MessageSquare', 'player')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 8. REALTIME
-- ============================================================================
DO $$
BEGIN
  -- Enable realtime for key tables
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE nm_staff_shifts; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE nm_cash_closings; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE nm_gym_access_logs; EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;
